### ISSUE TITLE
google.api_core.exceptions.NotFound

### ISSUE THREAD

**Issue by skoop12** [uchicago-cloud/mpcs51033-2019-autumn#8]
I've followed all the steps in the session notes from last class to set up my backend app engine and storage bucket, but I'm running into errors.  The site runs fine, but when I select a photo and click submit, I get an error message (shown in photo below).  

I've updated the CLOUD_STORAGE_BUCKET environment variable in the app.yaml file to photo-timeline-python3-1 (my project ID), but should it be something else?  

The only other part that is different from the steps is the path to my key - should that be the full path or project path?  I've tried both and keep getting the error so I don't know if it's related.

Please let me know if anyone has had this problem and found a solution!

![Screen Shot 2019-10-09 at 2 18 26 PM](https://user-images.githubusercontent.com/37815199/66512960-b04c4980-ea9f-11e9-8a1f-6a142fcef3c1.png)

**Comment by tabinks** [comment]
I ran into this problem too when I was working on it. It was related to the key.json file (at least for me). I put the full path in. If you have spaces in your path (eg. My Homework), then make sure to put "" around the path.

Did you try to deploy? Try that and see if it works. If it is related to some oddity because of paths on your local machine, it should work on Google's servers.

**Comment by skoop12** [comment]
Ok thanks!  My issue was actually with the billing account (in case anyone else is having this problem and the key path is correct), but now it is working in both the virtual env and deployed
